# file: .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  # Allow manual deployments
  workflow_dispatch:

permissions:
  contents: write   # Allow write access to the repository contents
  pages: write      # Allow write access to GitHub Pages
  id-token: write   # For authentication when deploying

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Upload static files (all files in the repository)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2   # Corrected version
        with:
          path: .  # Upload everything in the repository (ensure your HTML, CSS, and JS are in the root)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
